//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AppointmentTable
{
    public int AppointmentID { get; set; }
    public System.DateTime AppointmentDate { get; set; }
    public System.TimeSpan AppointmentTime { get; set; }
    public int DoctorID { get; set; }
    public int PatientID { get; set; }
    public string Description { get; set; }

    public virtual DoctorTable DoctorTable { get; set; }
    public virtual PatientTable PatientTable { get; set; }
}

public partial class DepartmentTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DepartmentTable()
    {
        this.DoctorTables = new HashSet<DoctorTable>();
    }

    public int DepartmentID { get; set; }
    public int HospitalID { get; set; }
    public string Specialization { get; set; }
    public string DepartmentEmail { get; set; }
    public string DepartmentPhone { get; set; }

    public virtual HospitalTable HospitalTable { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DoctorTable> DoctorTables { get; set; }
}

public partial class DoctorTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DoctorTable()
    {
        this.AppointmentTables = new HashSet<AppointmentTable>();
        this.PatientTables = new HashSet<PatientTable>();
    }

    public int DoctorID { get; set; }
    public int DepartmentID { get; set; }
    public string Name { get; set; }
    public string DoctorUserName { get; set; }
    public string DoctorEmail { get; set; }
    public string DoctorPhone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
    public virtual DepartmentTable DepartmentTable { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PatientTable> PatientTables { get; set; }
}

public partial class EmailTable
{
    public int EmailID { get; set; }
    public string EmailText { get; set; }
    public string DoctorUserName { get; set; }
    public string PatientUserName { get; set; }
    public System.DateTime EmailDate { get; set; }
    public System.TimeSpan EmailTime { get; set; }
}

public partial class HospitalTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HospitalTable()
    {
        this.DepartmentTables = new HashSet<DepartmentTable>();
    }

    public int HospitalID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string ContactEmail { get; set; }
    public string ContactPhone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DepartmentTable> DepartmentTables { get; set; }
}

public partial class PatientTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PatientTable()
    {
        this.AppointmentTables = new HashSet<AppointmentTable>();
    }

    public int PatientID { get; set; }
    public int DoctorID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string PatientUserName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
    public virtual DoctorTable DoctorTable { get; set; }
}
